language: java

jdk: openjdk11

before_install:
  - chmod +x gradlew

stage:
  - dev
  - prod


jobs:
  include:
    - stage: dev
      name: "build & unit test & sonar qube"
      script:
      - gradle build
      - gradle test
      - echo "I want to evaluate static quality code"

    - script: echo "I want to deploy to heroku"
      name: "deploy"





