language: java

jdk: openjdk11

before_install:
  - chmod +x gradlew

stage:
  - dev
  - prod


jobs:
  include:
    - stage: dev
      name: "build"
      script: echo "I want to build"
    - script: echo "I want to unit test"
      name: "unit test"
    - script: echo "I want to evaluate static quality code"
      name: "Sonar Qube"





