version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - [Your_Path_To_Scripts]:/docker-entrypoint-initdb.d
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evidence-based-management
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: ebm:0.0.1
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATABASE_URL=jdbc:postgresql://postgres:5432/evidence-based-management
      - JWTKEY=rgQKOB31fA!p
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres